#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyrsistent
Version  : 0.14.9
Release  : 27
URL      : https://files.pythonhosted.org/packages/45/5a/a1a446eba4b5bf9f823fd863605df24327e49241d6b5c43d82b429228caa/pyrsistent-0.14.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/45/5a/a1a446eba4b5bf9f823fd863605df24327e49241d6b5c43d82b429228caa/pyrsistent-0.14.9.tar.gz
Summary  : Persistent/Functional/Immutable data structures
Group    : Development/Tools
License  : MIT
Requires: pyrsistent-python = %{version}-%{release}
Requires: pyrsistent-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pytest-runner
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
Patch1: 0001-tests.patch

%description
Pyrsistent
==========
.. image:: https://travis-ci.org/tobgu/pyrsistent.png?branch=master
:target: https://travis-ci.org/tobgu/pyrsistent

%package python
Summary: python components for the pyrsistent package.
Group: Default
Requires: pyrsistent-python3 = %{version}-%{release}

%description python
python components for the pyrsistent package.


%package python3
Summary: python3 components for the pyrsistent package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyrsistent package.


%prep
%setup -q -n pyrsistent-0.14.9
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546872914
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
